apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets-mgr-ap-key
  namespace: kube-system
spec:
  encryptedData:
    apiKey: AgAVfKdLcv8cu168oC0uK4R/q/vAkfAuZDwrUBtOKnyAd75yyv0kq/TeIGmbL6/x8C9kkkGXKVbBQBudKioFqpucS05dhRDGvVcV+2X5kl3Jhof926AJTc6E7/11FF5mG277LojmRzZ6X1ZsuvyXqMur1IUh8NRPMEN4SCyVrJB4wKVYiN4RHLrN/Z0bM7ye4oFivd4eLWhu4OlhaPAFxS9xE22CnRrnF72e0FORG47fi/d80iLKCSaT8gKtkGd6TBjh3oEfJZV0qPinmkQQhZOy7/QmzKX9FPv+Tt6SBIIqGcRsB4mGrHuWdUStwyRj1WCRYQgZxl5xPJizBy7m00RYApEvj0M6rlBk0bMeGPlf4ZKRLb+L0kiY5GXnnO+zR3QUBt8RTLqClE3byEcGvieq+oBekkwzfv++x7SYxceC3S5WSWTk8IsM52fGRJhf+jDJN6LssSQf+PE3NVNAhGwVGQEHevMYPuASFuXF4SjpeU1QQc4KgVKxTKS1A0a5hWaC78Mq6jsurKFn9bNXprWdK7R247DjyvOAHo07GmZZ+ujdwjq6NQngRSl0xrFtmO75vLjUXGUqvFVZzx5hV+HF+EFiv8NGgTXbWqXBP+wgNcS4c0HR0AyEoyzK1Ap/wa3xkvQSEgRzmAzswzRLFRr0l2p8NuUSdwwHwJQLE9qOMlgykzmgXiZJklt4r6klNBZejSKzTb0CVCoMna/1nqRucptoleJc7LvrCYRMBj1F0iIklGLN9O2TQJJzMA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: secrets-mgr-ap-key
      namespace: kube-system